{
  "openapi": "3.0.0",
  "info": {
    "title": "Market",
    "description": "Market is an API for a simples store.",
    "contact": {
      "name": "API Support",
      "url": "http://www.market.com/support",
      "email": "market@email.com"
    },
    "version": "1.0.0"
  },

  "servers": [
    {
      "url": "https://market-products.herokuapp.com/api",
      "description": "Production server"
    },
    {
      "url": "http://localhost:3000/",
      "description": "Local Server"
    }
  ],
  "paths": {
    "/user": {
      "post": {
        "summary": "User register",
        "description": "This route registers users",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "user": {
                  "value": {
                    "name": "julia matos",
                    "email": "jumgc@gmail.com",
                    "password": "12345",
                    "isAdm": true
                  }
                }
              },
              "schema": { "$ref": "#/components/schemas/User" }
            }
          }
        },
        "responses": {
          "400": {
            "description": "E-mail already exists"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Lists all users",
        "description": "This routes returns all users",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "401": {
            "description": "Missing authorization headers"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ArrayOfUsers"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}": {
      "get": {
        "summary": "Searches for an user",
        "description": "This route returns a specific user information",
        "tags": ["User"],
        "security": [{ "bearerAuth": [] }],

        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "User id",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Missing authorization headers"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "User login",
        "description": "This route allows the user to login ",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/LoginUser" }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Wrong email/password"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "token": {
                    "value": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg2YjE1NGFmLTY2MGQtNDljZS1hMjdmLWM3MmNhNzE5ZThlNyIsImlhdCI6MTY0NDMyODUxOSwiZXhwIjoxNjQ0NDE0OTE5fQ.xMLms7EYiFJnOrhecq8nczpnbAAQ-j7G8zuMuRm-STc"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": { "token": { "type": "string" } }
                }
              }
            }
          }
        }
      }
    },
    "/product": {
      "post": {
        "summary": "Registers a product",
        "description": "This route registers a product",
        "tags": ["Products"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Product"
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "A product with this name already exists"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "examples": {
                  "product": {
                    "value": {
                      "name": "table",
                      "price": 10,
                      "description": "Glass table",
                      "created_at": "2022-02-14T16:32:35.756Z",
                      "updated_at": "2022-02-14T16:32:35.756Z",
                      "id": 7
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Product"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Lists all products",
        "description": "This route return a list of all products",
        "tags": ["Products"],

        "responses": {
          "401": {
            "description": "Missing authorization headers"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/ArrayOfProducts"
                }
              }
            }
          }
        }
      }
    },
    "/product/{id}": {
      "get": {
        "summary": "Searches for a specific product",
        "description": "This route returns a specific product",
        "tags": ["Products"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "product id",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "404": {
            "description": "Product not found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "product": {
                    "value": {
                      "name": "table",
                      "price": 10,
                      "description": "Glass table",
                      "created_at": "2022-02-14T16:32:35.756Z",
                      "updated_at": "2022-02-14T16:32:35.756Z",
                      "id": 7
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Product"
                }
              }
            }
          }
        }
      }
    },
    "/cart": {
      "post": {
        "summary": "Add a product to users cart",
        "description": "This route adds a product to the users cart",
        "tags": ["Carts"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/PostCart"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Product doesnâ€™t exist"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "examples": {
                  "cart": {
                    "value": {
                      "id": "118857cb-007c-490a-bbf6-c555fd9c2fad",
                      "createdOn": "2022-02-09T17:41:56.217Z",
                      "updatedOn": "2022-02-09T17:41:56.217Z",
                      "products": [
                        {
                          "id": 4,
                          "cartId": "118857cb-007c-490a-bbf6-c555fd9c2fad",
                          "created_at": "2022-02-09T18:09:25.552Z",
                          "updated_at": "2022-02-09T18:19:45.837Z",
                          "quantity": 2,
                          "product": {
                            "id": 1,
                            "name": "string",
                            "price": 10,
                            "description": "string",
                            "created_at": "2022-02-09T17:21:51.374Z",
                            "updated_at": "2022-02-09T17:21:51.374Z"
                          }
                        }
                      ],
                      "total": 20
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Cart"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Lists all carts",
        "description": "This route lists all carts",
        "tags": ["Carts"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/ArrayOfCarts"
                }
              }
            }
          }
        }
      }
    },
    "/cart/{id}": {
      "get": {
        "summary": "Searches for a specific cart",
        "description": "This route returns a specific cart",
        "tags": ["Carts"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "cart id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "404": {
            "description": "Cart not found"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "examples": {
                  "cart": {
                    "value": {
                      "id": "118857cb-007c-490a-bbf6-c555fd9c2fad",
                      "createdOn": "2022-02-09T17:41:56.217Z",
                      "updatedOn": "2022-02-09T17:41:56.217Z",
                      "products": [
                        {
                          "id": 4,
                          "cartId": "118857cb-007c-490a-bbf6-c555fd9c2fad",
                          "created_at": "2022-02-09T18:09:25.552Z",
                          "updated_at": "2022-02-09T18:19:45.837Z",
                          "quantity": 2,
                          "product": {
                            "id": 1,
                            "name": "string",
                            "price": 10,
                            "description": "string",
                            "created_at": "2022-02-09T17:21:51.374Z",
                            "updated_at": "2022-02-09T17:21:51.374Z"
                          }
                        }
                      ],
                      "total": 20
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Cart"
                }
              }
            }
          }
        }
      }
    },
    "/buy": {
      "post": {
        "summary": "Makes an order",
        "description": "Makes an order and sends an e-mail to the user",
        "tags": ["Orders"],
        "security": [{ "bearerAuth": [] }],

        "responses": {
          "404": {
            "description": "User not found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Order"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Lists all orders",
        "description": "This route returns all users orders",
        "tags": ["Orders"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/ArrayOfOrders"
                }
              }
            }
          }
        }
      }
    },
    "/buy/{id}": {
      "get": {
        "summary": "Searches for a specific order",
        "description": "This route returns a specific order",
        "tags": ["Orders"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "order id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "404": {
            "description": "Order not found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Order"
                }
              }
            }
          }
        }
      }
    },
    "/email": {
      "post": {
        "summary": "Sends an e-mail to an user",
        "description": "This route send an e-mail to an user",
        "tags": ["Email"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Email"
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "201": {
            "description": "Email was sent."
          }
        }
      }
    },

    "/recuperar": {
      "post": {
        "summary": "Sends a code to the user",
        "description": "This route sends a code to the user to change password",
        "tags": ["Recuperar"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Recuperar"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "User not found"
          },
          "201": {
            "description": "Email with the code to retrieve your password was sent."
          }
        }
      }
    },

    "/alterar_senha": {
      "post": {
        "summary": "Changes users password",
        "description": "This route changes users password",
        "tags": ["Password"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Password"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "User not found"
          },
          "201": {
            "description": "Your password was changed."
          }
        }
      }
    }
  },

  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "LoginUser": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Password": {
        "type": "object",
        "required": ["email", "password", "code", "confirmation"],
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "code": {
            "type": "string"
          },
          "confirmation": {
            "type": "string"
          }
        }
      },
      "Recuperar": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string"
          }
        }
      },
      "Email": {
        "type": "object",
        "required": ["email", "subject", "text"],
        "properties": {
          "email": {
            "type": "string"
          },
          "subject": {
            "type": "string"
          },
          "text": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "isAdm": {
            "type": "boolean"
          },
          "uuid": {
            "type": "string",
            "format": "uuid"
          }
        },
        "example": {
          "id": "b24acbef-1d9a-4cd3-a6b1-86c1c9f69585",
          "name": "Ju",
          "email": "ADM@gmail.com",
          "isAdm": true,
          "createdOn": "2022-02-10T14:19:29.745Z",
          "updatedOn": "2022-02-10T14:19:29.752Z",
          "cart": {
            "id": "ab2c5d0d-a328-4078-9e3b-85b67f4c29f7",
            "createdOn": "2022-02-10T14:19:29.752Z",
            "updatedOn": "2022-02-10T14:19:29.752Z",
            "products": []
          }
        }
      },
      "Product": {
        "type": "object",
        "required": ["name", "price", "description"],
        "properties": {
          "name": {
            "type": "string"
          },
          "price": {
            "type": "number"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "ArrayOfProducts": {
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#components/schemas/Product"
        },
        "example": [
          {
            "id": 1,
            "name": "Jar",
            "description": "A green glass jar",
            "created_at": "2022-02-06T22:20:31.722Z",
            "updated_at": "2022-02-06T22:20:31.722Z"
          },
          {
            "id": 2,
            "name": "Mirror",
            "description": "A 1x1m mirror",
            "created_at": "2022-02-06T22:20:31.722Z",
            "updated_at": "2022-02-06T22:20:31.722Z"
          }
        ]
      },
      "Cart": {
        "type": "object",
        "properties": {
          "productId": {
            "type": "number"
          },
          "createdOn": {
            "type": "number"
          },
          "updatedOn": {
            "type": "number"
          },
          "quantity": {
            "type": "number"
          },
          "product": {}
        }
      },
      "PostCart": {
        "type": "object",
        "properties": {
          "productId": {
            "type": "number"
          }
        }
      },
      "ArrayOfCarts": {
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#components/schemas/Cart"
        },
        "example": [
          {
            "id": "c1b1a4a7-d8d4-449b-ba7f-5fbc505c15ba",
            "createdOn": "2022-02-09T17:08:17.164Z",
            "updatedOn": "2022-02-09T17:08:17.164Z",
            "updated_at": "2022-01-14T21:22:39.858Z",
            "products": [
              {
                "id": 2,
                "cartId": "5ad41564-c7fd-421d-9c30-eb40217149f3",
                "created_at": "2022-02-09T17:53:45.423Z",
                "updated_at": "2022-02-09T17:53:45.423Z",
                "quantity": 1,
                "product": {
                  "id": 1,
                  "name": "string",
                  "price": 0,
                  "description": "string",
                  "created_at": "2022-02-09T17:21:51.374Z",
                  "updated_at": "2022-02-09T17:21:51.374Z"
                }
              }
            ]
          }
        ]
      },
      "ArrayOfUsers": {
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#components/schemas/User"
        },
        "example": [
          {
            "id": "b24acbef-1d9a-4cd3-a6b1-86c1c9f69585",
            "name": "Ju",
            "email": "ADM@gmail.com",
            "isAdm": true,
            "createdOn": "2022-02-10T14:19:29.745Z",
            "updatedOn": "2022-02-10T14:19:29.752Z",
            "cart": {
              "id": "ab2c5d0d-a328-4078-9e3b-85b67f4c29f7",
              "createdOn": "2022-02-10T14:19:29.752Z",
              "updatedOn": "2022-02-10T14:19:29.752Z",
              "products": []
            }
          },
          {
            "id": "7d5209d1-5b83-489c-b1ee-e74bc164f584",
            "name": "Ju",
            "email": "adminis4@gmail.com",
            "isAdm": true,
            "createdOn": "2022-02-10T16:14:27.174Z",
            "updatedOn": "2022-02-10T16:14:27.191Z",
            "cart": {
              "id": "b00eeb5a-5b87-473a-8e6c-e615d847e982",
              "createdOn": "2022-02-10T16:14:27.191Z",
              "updatedOn": "2022-02-10T16:14:27.191Z",
              "products": []
            }
          }
        ]
      },
      "Order": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "total": {
            "type": "object",
            "$ref": "#/components/schemas/User"
          },
          "userId": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          },
          "products": {
            "type": "array",
            "$ref": "#/components/schemas/ArrayOfProducts"
          }
        },
        "example": {
          "Order": {
            "id": "bba62544-1b75-42fe-a56b-165258ca1029",
            "createdOn": "2022-02-14T16:17:39.467Z",
            "Done": false,
            "userId": "55f82ced-f785-4776-b248-275554395604",
            "products": [
              {
                "id": 18,
                "orderId": "bba62544-1b75-42fe-a56b-165258ca1029",
                "created_at": "2022-02-14T16:17:39.483Z",
                "updated_at": "2022-02-14T16:17:39.483Z",
                "quantity": 1,
                "product": {
                  "id": 5,
                  "name": "door",
                  "price": 10,
                  "description": "great set of golden keys",
                  "created_at": "2022-02-10T14:19:50.818Z",
                  "updated_at": "2022-02-10T14:19:50.818Z"
                }
              }
            ]
          },
          "total": 10
        }
      },
      "ArrayOfOrders": {
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#components/schemas/Order"
        },
        "example": [
          {
            "id": "127839ae-959f-4af6-9c2d-1fb31b6b5475",
            "createdOn": "2022-02-10T14:21:49.328Z",
            "Done": true,
            "userId": "72bde105-3984-4a8d-8351-1c4e99317aac",
            "products": [
              {
                "id": 16,
                "orderId": "127839ae-959f-4af6-9c2d-1fb31b6b5475",
                "created_at": "2022-02-10T14:21:49.336Z",
                "updated_at": "2022-02-10T14:22:54.364Z",
                "quantity": 1,
                "product": {
                  "id": 5,
                  "name": "door",
                  "price": 10,
                  "description": "great set of golden keys",
                  "created_at": "2022-02-10T14:19:50.818Z",
                  "updated_at": "2022-02-10T14:19:50.818Z"
                }
              },
              {
                "id": 17,
                "orderId": "127839ae-959f-4af6-9c2d-1fb31b6b5475",
                "created_at": "2022-02-10T17:31:00.404Z",
                "updated_at": "2022-02-10T17:31:00.404Z",
                "quantity": 1,
                "product": {
                  "id": 5,
                  "name": "door",
                  "price": 10,
                  "description": "great set of golden keys",
                  "created_at": "2022-02-10T14:19:50.818Z",
                  "updated_at": "2022-02-10T14:19:50.818Z"
                }
              }
            ]
          }
        ]
      }
    }
  }
}
